manifest:
  remotes:
    - name: JsmnRepo
      url-base: https://github.com/zserge
    - name: LairdCP
      url-base: https://github.com/LairdCP

  # Please add items below based on alphabetical order.
  # These dependencies may need updating if new features are added to the firmware.
  projects:
    - name: attributes
      path: modules/attributes
      revision: 5a56aad47e94950e8301708da5f30cb9fcf7515f
      remote: LairdCP
    - name: zephyr_framework
      path: modules/framework
      revision: 83f6016390290b30c93bb55b854051bbcde532b9
      remote: LairdCP
    - name: jsmn
      path: modules/jsmn
      revision: 7b6858a5855299d173c5ab2b46e611bf9961cbef
      remote: JsmnRepo
    - name: BLE_Gateway_Firmware
      path: ble_gateway_firmware
      revision: 610a780c508c52f4edb9d9fc022d14c4dcef9d9a
      remote: LairdCP
    - name: sdk-nrf
      path: nrf
      revision: v1.7.0
      remote: LairdCP
      import: true
    - name: zephyr
      revision: 0f11885cc36fe5a13812a582268867ed59f7dc1b
      remote: LairdCP
      import:
        # In addition to the zephyr repository itself, NCS also
        # imports the contents of zephyr/west.yml.
        # Only the projects explicitly named in the
        # following whitelist are imported.
        #
        # Note that the zephyr west extensions (like 'build', 'flash',
        # 'debug', etc.) are automatically provided by this import, so
        # there's no need to add a redundant west-commands: key for
        # the zephyr project.
        #
        # Please keep this list sorted alphabetically.
        name-whitelist:
          - cmsis
          - fatfs
          - hal_nordic
          - libmetal
          - littlefs
          - mbedtls
          - mcumgr
          - mipi-sys-t
          - net-tools
          - nrf_hw_models
          - open-amp
          - openthread
          - segger
          - tinycbor
          - tinycrypt
    - name: zephyr_boards
      path: boards/arm
      revision: e529f3c110dd661f1d10f84ad325a7c0238411c9
      remote: LairdCP
    - name: zephyr_lib
      path: modules/zephyr_lib
      revision: 3f49268509e2026d7c8c8e285d8f24a783979d8b
      remote: LairdCP

  self:
    path: pinnacle_100_firmware_public_manifest
